#!/usr/bin/env bash

clear

CHOICE=$(
gum choose \
    "Install a Web App" \
    "Uninstall Web Apps"
)

case "$CHOICE" in
    "Install a Web App")
        exec "$(dirname "$0")/install-web-apps"
        ;;
    "Uninstall Web Apps")
        exec "$(dirname "$0")/uninstall-web-apps"
        ;;
esac
